Run shellcheck on all bash code
This cleans up all bash to match shellcheck recommendations, including
*.bats test files

Signed-off-by: Jim Ramsay <jramsay@redhat.com>

diff --git a/utils/kubensenter/kubensenter b/utils/kubensenter/kubensenter
--- a/utils/kubensenter/kubensenter
+++ b/utils/kubensenter/kubensenter
@@ -1,17 +1,27 @@
 #!/bin/bash
 
+# shellcheck disable=SC2016
 usage() {
     echo "A command line wrapper to run commands or shells inside the"
     echo "kubens.service mount namespace."
     echo
     echo "Usage:"
-    echo "    $(basename $0) [--verbose|--quiet] [command ...]"
+    echo "    $(basename "$0") [--verbose|--quiet] [command ...]"
     echo
-    echo "Autodetect whether the kubens.service has pinned a mount namespace in a"
-    echo "well-known location, and if so, join it by passing it and the"
-    echo "user-specified command to nsenter(1). If kubens.service has not set up"
-    echo "the mount namespace, the user-specified command is still passed to"
-    echo "nsenter(1) but no namespace is entered."
+    echo 'Autodetect whether the `kubens.service` has pinned a mount namespace in a'
+    echo 'well-known location, and if so, join it by passing it and the user-specified'
+    echo 'command to nsenter(1). If `kubens.service` has not set up the mount namespace,'
+    echo 'the user-specified command is still executed by nsenter(1) but no namespace is'
+    echo 'entered.'
+    echo
+    echo 'If $KUBENSMNT is set in the environment, skip autodetection and attempt to join'
+    echo 'that mount namespace by passing it and the user-specified command to'
+    echo 'nsenter(1). If the mount namespace is missing or invalid, the command will'
+    echo 'fail.'
+    echo
+    echo 'In either case, if no command is given on the command line, nsenter(1) will'
+    echo 'spawn a new interactive shell which will be inside the mount namespace if'
+    echo 'detected.'
     exit 1
 }
 
@@ -19,25 +29,26 @@ LOGLEVEL=${KUBENSENTER_LOG:-1}
 _log() {
     local level=$1; shift
     if [[ $level -le $LOGLEVEL ]]; then
-        echo "kubensenter: $@" >&2
+        echo "kubensenter: $*" >&2
     fi
 }
 
 info() {
-    _log 1 "$@"
+    _log 1 "$*"
 }
 
 debug() {
-    _log 2 "$@"
+    _log 2 "$*"
 }
 
 # Returns 0 if the argument given is a mount namespace
 ismnt() {
-    local nsfs=$(findmnt -o SOURCE -n -t nsfs "$1")
-    [[ $nsfs =~ nsfs\[mnt:\[ ]]
+    local nsfs
+    nsfs=$(findmnt -o SOURCE -n -t nsfs "$1")
+    [[ $nsfs =~ ^nsfs\[mnt:\[ ]]
 }
 
-# Sets KUBENSMNT if it's not already
+# Set KUBENSMNT to the default location that kubens.service uses if KUBENSMNT isn't already set.
 DEFAULT_KUBENSMNT=${DEFAULT_KUBENSMNT:-"/run/kubens/mnt"}
 autodetect() {
     local default=$DEFAULT_KUBENSMNT
@@ -58,7 +69,7 @@ autodetect() {
     return 0
 }
 
-# If KUBENSMNT is set, run nsenter to join that mountspace
+# Wrap the user-given command in nsenter, joining the mount namespace set in $KUBENSMNT if set
 kubensenter() {
     local nsarg
     if [[ -n $KUBENSMNT ]]; then
@@ -66,7 +77,12 @@ kubensenter() {
         nsarg=$(printf -- "--mount=%q" "$KUBENSMNT")
     else
         debug "KUBENSMNT not set; running normally"
+        # Intentional fallthrough to run nsenter anyway:
+        # - If $@ is non-empty, nsenter effectively runs `exec "$@"`
+        # - If $@ is empty, nsenter spawns a new shell
     fi
+    # shellcheck disable=SC2086
+    # ^- Intentionally collapse $nsarg if not set (and we've already shell-quoted it above if we did set it)
     nsenter $nsarg "$@"
 }
 
@@ -95,4 +111,4 @@ main() {
 }
 
 # bash modulino
-[[ "$BASH_SOURCE" == "$0" ]] && main "$@"
+[[ "${BASH_SOURCE[0]}" == "$0" ]] && main "$@"
